export const EVENTS = {
	CREATE_USER: 'CREATE_USER',
	INIT_BALANCE: 'INIT_BALANCE',
	REFERRAL_CREDIT: 'REFERRAL_CREDIT',
	VERIFICATION_STATUS_UPDATE: 'VERIFICATION_STATUS_UPDATE',
	GET_BALANCE: 'GET_BALANCE',
	DEPOSIT_BALANCE: 'DEPOSIT_BALANCE',
} as const;
