services:
  postgres:
    image: postgres:16-alpine
    container_name: probo-database
    restart: always
    environment:
      POSTGRES_USER: probo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - '5432:5432'
    volumes:
      - probo_database_data:/var/lib/postgresql/data

  redis-cache:
    image: redis:7.2
    container_name: probo-redis-cache
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-cache-data:/data

  redis-pubsub:
    image: redis:7.2
    container_name: probo-redis-pubsub
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis-pubsub-data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  probo_database_data:
  redis-cache-data:
  redis-pubsub-data:
