package types

type EVENTS string

const (
	INCREASE_TRADERS_COUNT EVENTS = "INCREASE_TRADERS_COUNT"
	UPDATE_STOCK_PRICE     EVENTS = "UPDATE_STOCK_PRICE"
	TRADE_EXECUTED         EVENTS = "TRADE_EXECUTED"
	ORDER_PLACED           EVENTS = "ORDER_PLACED"
	SHARES_SPLIT           EVENTS = "SHARES_SPLIT"
	SHARES_MERGED          EVENTS = "SHARES_MERGED"
)
