package types

type EVENTS string

const (
	INCREASE_TRADERS_COUNT EVENTS = "INCREASE_TRADERS_COUNT"
	UPDATE_MARKET_TIMELINE EVENTS = "UPDATE_MARKET_TIMELINE"
	UPDATE_STOCK_PRICE     EVENTS = "UPDATE_STOCK_PRICE"
	RECORD_ACTIVITY        EVENTS = "RECORD_ACTIVITY"
	ORDER_PLACED           EVENTS = "ORDER_PLACED"
)
