export const DB_EVENTS = {
	INCREASE_TRADERS_COUNT: 'INCREASE_TRADERS_COUNT',
	UPDATE_STOCK_PRICE: 'UPDATE_STOCK_PRICE',
	UPDATE_MARKET_TIMELINE: 'UPDATE_MARKET_TIMELINE',
	RECORD_ACTIVITY: 'RECORD_ACTIVITY',
	ORDER_PLACED: 'ORDER_PLACED',
} as const;
